# Default values for .openshift.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repository:
  kind: nexus
  url: http://sonatype-nexus-service.nexus.svc.cluster.local:8081/repository/helm-charts/

charts:
  - name: deployment
    enabled: true
    dir: charts/deployment/
  - name: serverless
    enabled: true
    dir: charts/serverless/

