# Default values for pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Default values for cicd-with-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

teamName: product-team

artifactRepository:
  url: https://nexus-nexus.apps.cluster-g8s6c.g8s6c.sandbox758.opentlc.com/
  repos:
    maven: repository/maven-public/
    npm: repository/labs-npm/

environments: &environments
  - name: dev
    kind: ci
    pvc: 1Gi
    ref:
      kind: heads
      name: develop
  - name: staging
    kind: cd
    previuosEnv: dev
    ref:
      kind: heads
      name: master
  - name: prod
    kind: cd
    previuosEnv: staging
    ref:
      kind: tags
      name: ^v.+

applications:
  - name: yaml-online
    enabled: true
    serverless: true
    repo: https://github.com/caiomedeirospinto/yaml-online.git
    project: yaml-online
    runtime:
      name: nodejs
      version: "14"
      libraries:
        - angular
        - nginx
    environments: *environments
  - name: yaml-ms-online-session
    enabled: true
    serverless: true
    repo: https://github.com/caiomedeirospinto/yaml-ms-online-session.git
    project: yaml-online
    runtime:
      name: java
      version: latest
      libraries:
        - quarkus
    environments: *environments
  - name: yaml-ws-online-session
    enabled: true
    serverless: false
    repo: https://github.com/caiomedeirospinto/yaml-ws-online-session.git
    project: yaml-online
    runtime:
      name: java
      version: latest
      libraries:
        - quarkus
    environments: *environments
