---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  params:
    - default: master
      name: GIT_REVISION
      type: string
    - default: 'https://github.com/caiomedeirospinto/ocp-gitops-demo.git'
      name: GIT_REPO
      type: string
    - default: 'nexus-credentials'
      name: NEXUS_CREDENTIALS_SECRET
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    {{- $root := . -}}
    {{- range $chart := .Values.charts }}
    {{- if $chart.enabled }}
    - name: helm-lint-{{ $chart.name }}
      params:
        - name: ARGS
          value:
            - lint
            - {{ $chart.dir }}
      taskRef:
        kind: Task
        name: helm-cli
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: workspace
    - name: helm-package-{{ $chart.name }}
      params:
        - name: ARGS
          value:
            - package
            - {{ $chart.dir }}
            - "--destination=./packages/"
      taskRef:
        kind: Task
        name: helm-cli
      runAfter:
        - helm-lint-{{ $chart.name }}
      workspaces:
        - name: source
          workspace: workspace
    {{- if eq $root.Values.repository.kind "nexus" }}
    - name: push-to-repo-{{ $chart.name }}
      params:
        - name: NEXUS_REPO_URL
          value: {{ $root.Values.repository.url }}
        - name: PACKAGE_PATH
          value: ./packages/{{ $chart.name }}*.tgz
        - name: CREDENTIALS_SECRET
          value: $(params.NEXUS_CREDENTIALS_SECRET)
      taskRef:
        kind: Task
        name: nexus-publish-package
      runAfter:
        - helm-package-{{ $chart.name }}
      workspaces:
        - name: packages
          workspace: workspace
    {{- end }}
    {{- end }}
    {{- end }}
  workspaces:
    - name: workspace
