kind: Secret
apiVersion: v1
metadata:
  name: nexus-credentials
  namespace: nexus
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  password: {{ .Values.repository.password }}
  username: {{ .Values.repository.username }}
type: Opaque
