kind: Secret
apiVersion: v1
metadata:
  name: nexus-credentials
  namespace: nexus
stringData:
  password: {{ .Values.repository.password }}
  username: {{ .Values.repository.username }}
type: Opaque
