---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.teamName }}
spec:
  serviceAccountName: {{ .Values.teamName }}-triggers
  triggers:
    {{- range $app := .Values.applications }}
    {{- range $env := $app.environments }}
    {{- if $app.enabled }}
    - name: {{ $app.name }}-{{ $env.name }}
      bindings:
        - kind: ClusterTriggerBinding
          {{- if eq "cd" $env.kind }}
          {{- if $app.is_gitlab }}
          ref: gitlab-push-cd
          {{- else }}
          ref: github-push-cd
          {{- end }}
          {{- else }}
          {{- if $app.is_gitlab }}
          ref: gitlab-push
          {{- else }}
          ref: github-push
          {{- end }}
          {{- end }}
      interceptors:
        {{- if eq "cd" $env.kind }}
        - name: truncate large commit SHA
          ref:
            name: cel
          params:
            - name: overlays
              value:
                - expression: body.head_commit.id.truncate(6)
                  key: truncated_sha
        {{- end }}
        - name: filter branch
          ref:
            name: cel
          params:
            - name: filter
              value: 'body.ref == "refs/{{ $env.ref.kind }}/{{ $env.ref.name }}" && body.repository.name == "{{ $app.name }}"'
      template:
        ref: {{ $app.name }}-{{ $env.name }}
    {{- end }}
    {{- end }}
    {{- end }}
