{{- range $app := .Values.applications }}
{{- range $env := $app.environments }}
{{- if and (eq "ci" $env.kind) ($app.enabled) (not $app.skip_build) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $app.name }}-{{ $env.kind }}
  namespace: {{ $app.project }}-{{ $env.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $env.pvc }}
  volumeMode: Filesystem
{{- end }}
{{- end }}
{{- end }}
