---
apiVersion: v1
kind: List
items:
{{- $name := include "pipelines.name" . }}
{{- $ns := .Release.Namespace }}
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ $name }}-triggers-sa-edit
      namespace: {{ $ns }}
    subjects:
      - kind: ServiceAccount
        name: {{ $name }}-triggers-sa
        namespace: {{ $ns }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
{{- range $app := .Values.apps }}
{{- if $app.enabled }}
{{- range $environment := $app.environments }}
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ $name }}-triggers-sa-edit
      namespace: {{ $app.project }}-{{ $environment.name }}
    subjects:
      - kind: ServiceAccount
        name: {{ $name }}-triggers-sa
        namespace: {{ $ns }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
{{- end }}
{{- end }}
{{- end }}
