---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipelines.name" . }}-triggers-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
