{{- range $app := .Values.applications }}
{{- range $env := $app.environments }}
{{- if $app.enabled }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ $app.name }}-{{ $env.name }}
spec:
  params:
    - name: git-revision
    {{- if eq "ci" $env.kind }}
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: pusher-name
    {{- end }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations: {}
        generateName: {{ $app.name }}-{{ $env.kind }}-
        namespace: {{ $app.project }}-{{ $env.name }}
        labels:
          tekton.dev/pipeline: {{ $app.name }}-{{ $env.kind }}
      spec:
        params:
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: app-name
            value: {{ $app.name }}
          {{- if eq "ci" $env.kind }}
          - name: git-url
            value: $(tt.params.git-repo-url)
          {{- else }}
          - name: previous-namespace
            value: {{ $app.project }}-{{ $env.previuosEnv }}
          {{- end }}
        pipelineRef:
          name: {{ $app.name }}-{{ $env.kind }}
        resources: []
        status: null
        {{- if and (eq "ci" $env.kind) (not $app.skip_build) }}
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: {{ $app.name }}-{{ $env.kind }}
          {{- if eq "java" $app.runtime.name }}
          - emptyDir: {}
            name: maven-settings
          {{- end }}
        {{- else }}
        workspaces: []
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
