kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi-quarkus-native-s2i
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '20.3'
      from:
        kind: DockerImage
        name: 'quay.io/quarkus/ubi-quarkus-native-s2i:20.3-java11'
      referencePolicy:
        type: Source
