kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
