{{- if .Values.configurationManager }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "serverless.name" . }}
  labels:
    {{- include "serverless.labels" . | nindent 4 }}
data:
{{- toYaml .Values.configurationManager | nindent 2 }}
{{- end }}
