kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ include "serverless.name" . }}
  labels:
    {{- include "serverless.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
