{{- if .Values.secrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "serverless.name" . }}
  labels:
    {{- include "serverless.labels" . | nindent 4 }}
stringData:
{{- toYaml .Values.secrets | nindent 2 }}
type: Opaque
{{- end }}
